package gerumap.gui.swing.Errori.FactoryMessageGenerator;

public enum MessageEnum {
    NE_MOZE_SE_BRISATI,
    NEPOPUNJEN_TEXTFIELD,
    NE_MOZE_SE_DODATI_DETE,
    NIJE_MOGUCE_PROMENITI_IME,
    NISTA_NIJE_SELEKTOVANO,
    NIJE_ODGOVARAJUCI_STATE,
    NIJE_BROJ,
    NE_POSTOJI_PROJEKAT,

    NIJE_SELEKTOVAN_PROJEKAT,
    ODABERITE_GLAVNI_POJAM,
}
